import and preprocessing the given datasets

In [ ]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/ml mini projects/movies.csv')

In [ ]:
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
data.shape

(4803, 24)

In [ ]:
selectedFeatures = ['genres','keywords','overview','tagline','cast','director']
print(selectedFeatures)

['genres', 'keywords', 'overview', 'tagline', 'cast', 'director']


In [ ]:
for feature in selectedFeatures:
  data[feature]=data[feature].fillna("")

In [ ]:
comFeatures = data['genres']+data['keywords']+data['overview']+data['tagline']+data['cast']+data['director']
print(comFeatures)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    When ambitious New York attorney Sam is sent t...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [ ]:
vector = TfidfVectorizer()
featureVector = vector.fit_transform(comFeatures)
print(featureVector)

  (0, 5503)	0.12851987506039134
  (0, 31084)	0.20972605417816464
  (0, 24304)	0.11729818028068979
  (0, 21473)	0.16694643157272987
  (0, 34830)	0.12048634402730937
  (0, 39854)	0.14758485475124714
  (0, 33482)	0.1547500805684794
  (0, 31984)	0.16503535093640637
  (0, 41168)	0.1442864101527829
  (0, 40687)	0.17981538373009082
  (0, 32030)	0.11257493992023024
  (0, 26552)	0.030363106625038827
  (0, 40649)	0.06976133045926865
  (0, 12442)	0.13880514542831832
  (0, 6723)	0.15863034384575367
  (0, 1382)	0.12048634402730937
  (0, 1656)	0.052019533237400384
  (0, 29134)	0.16007780288612455
  (0, 1693)	0.030441494970065937
  (0, 26831)	0.1547500805684794
  (0, 14579)	0.13820066347113272
  (0, 3839)	0.095124443735071
  (0, 37269)	0.14006205467854133
  (0, 3482)	0.09341830651998566
  (0, 5303)	0.059028576219542425
  :	:
  (4802, 37757)	0.07843764997361562
  (4802, 36424)	0.05974550873970907
  (4802, 26349)	0.06108180610873494
  (4802, 16664)	0.07795031657907454
  (4802, 39941)	0.0770180406882288

In [ ]:
similarity = cosine_similarity(featureVector)
print(similarity)
similarity.shape

[[1.         0.04651794 0.02122374 ... 0.02538798 0.03210693 0.00612798]
 [0.04651794 1.         0.03945313 ... 0.04955816 0.03187544 0.01488931]
 [0.02122374 0.03945313 1.         ... 0.02570582 0.01200746 0.01342171]
 ...
 [0.02538798 0.04955816 0.02570582 ... 1.         0.03869624 0.02633318]
 [0.03210693 0.03187544 0.01200746 ... 0.03869624 1.         0.03292613]
 [0.00612798 0.01488931 0.01342171 ... 0.02633318 0.03292613 1.        ]]


(4803, 4803)

Now we are moving into recommendation algorithm

In [ ]:
movieName = input('Enter your favourite movie name: ')

Enter your favourite movie name: batman


In [ ]:
listTitles = data['title'].tolist()
print(listTitles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
findCloseMatch = difflib.get_close_matches(movieName,listTitles)
print(findCloseMatch)

['Batman', 'Batman', 'Catwoman']


In [ ]:
closeMatch=findCloseMatch[0]
print(closeMatch)

Batman


In [ ]:
movieIndex = data[data.title == closeMatch]['index'].values[0]
print(movieIndex)

1359


In [ ]:
similarityScore = list(enumerate(similarity[movieIndex]))
print(similarityScore)

[(0, 0.024240753071863706), (1, 0.04334605036090619), (2, 0.011248922190355691), (3, 0.19608222216837629), (4, 0.03047009280844211), (5, 0.034578778797751286), (6, 0.020845641397248097), (7, 0.021302244189467204), (8, 0.07458137962827843), (9, 0.1013429960176549), (10, 0.07347861770600597), (11, 0.01844355970095584), (12, 0.04222130369110673), (13, 0.014334368505688571), (14, 0.08284426738077072), (15, 0.0288071152233001), (16, 0.03807273892838978), (17, 0.042920383232948535), (18, 0.04646815312894652), (19, 0.03364301243640301), (20, 0.04307461753217277), (21, 0.04530477377058975), (22, 0.017366841132997097), (23, 0.011138545387241), (24, 0.02709932758798099), (25, 0.032429181435833086), (26, 0.0273489545291234), (27, 0.030969276931780122), (28, 0.005041112878279461), (29, 0.020988150918679473), (30, 0.07590582644665761), (31, 0.018012285047060712), (32, 0.045070303461244327), (33, 0.00794487727043757), (34, 0.006343044848153522), (35, 0.025105298815481875), (36, 0.0557104640978059), 

In [ ]:
SortedSimilarMovies=sorted(similarityScore, key = lambda x:x[1],reverse=True)
print(SortedSimilarMovies)

[(1359, 1.0), (119, 0.2066326416068963), (210, 0.2007473005096487), (3, 0.19608222216837629), (428, 0.19508744891201862), (65, 0.1649467621828425), (299, 0.15765873415748494), (3854, 0.14535121803923992), (9, 0.1013429960176549), (1469, 0.09685389589937182), (1390, 0.08718899547309922), (4759, 0.0864543942661844), (14, 0.08284426738077072), (870, 0.08160048835537055), (1803, 0.0806147946362485), (72, 0.0805114549242314), (2365, 0.080418805260777), (4558, 0.08009503881358408), (813, 0.07942709212478785), (30, 0.07590582644665761), (1296, 0.07579697187616063), (1247, 0.07507357306022472), (2858, 0.07501197515448745), (1085, 0.07472276604254076), (8, 0.07458137962827843), (3600, 0.07450474297496767), (1421, 0.07394125727446453), (10, 0.07347861770600597), (1017, 0.07283802241840105), (4392, 0.07243192593965511), (1141, 0.07235761197052007), (2885, 0.0721359295275899), (1477, 0.07202675996155117), (2265, 0.07199412875206973), (831, 0.07159767818125955), (1076, 0.07132380060878969), (602, 0

In [ ]:
print("Movie suggest for you : \n")
i=1
for movie in SortedSimilarMovies:
  index = movie[0]
  titlefromIndex = data[data.index==index]["title"].values[0]
  if(i<=30):
    print(i,".",titlefromIndex)
    i+=1

Movie suggest for you : 

1 . Batman
2 . Batman Begins
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Returns
6 . The Dark Knight
7 . Batman Forever
8 . Batman: The Dark Knight Returns, Part 2
9 . Batman v Superman: Dawn of Justice
10 . Chill Factor
11 . Underworld: Rise of the Lycans
12 . The Image Revolution
13 . Man of Steel
14 . Superman II
15 . Blood and Wine
16 . Suicide Squad
17 . Nine 1/2 Weeks
18 . Alleluia! The Devil's Carnival
19 . Superman
20 . Spider-Man 2
21 . Superman III
22 . City By The Sea
23 . The Postman Always Rings Twice
24 . Multiplicity
25 . Harry Potter and the Half-Blood Prince
26 . Halloween 4: The Return of Michael Myers
27 . Hoffa
28 . Superman Returns
29 . Bedazzled
30 . Safe Men


Movie Recommendation System

In [ ]:
try:
  movieName = input('Enter your favourite movie name: ')

  listTitles = data['title'].tolist()

  findCloseMatch = difflib.get_close_matches(movieName,listTitles)

  closeMatch=findCloseMatch[0]

  movieIndex = data[data.title == closeMatch]['index'].values[0]

  similarityScore = list(enumerate(similarity[movieIndex]))

  SortedSimilarMovies=sorted(similarityScore, key = lambda x:x[1],reverse=True)

  print("Movie suggest for you : \n")
  i=1
  for movie in SortedSimilarMovies:
    index = movie[0]
    titlefromIndex = data[data.index==index]["title"].values[0]
    if(i<=30):
      print(i,".",titlefromIndex)
      i+=1
except:
  print("oops the movie you are searching is not found in the dataset.we will soon update the dataset")

Enter your favourite movie name: superman
Movie suggest for you : 

1 . Superman
2 . Superman IV: The Quest for Peace
3 . Superman II
4 . Superman Returns
5 . Superman III
6 . Man of Steel
7 . Suicide Squad
8 . Mars Attacks!
9 . Kick-Ass 2
10 . Our Idiot Brother
11 . Iron Man 2
12 . Megamind
13 . Rise of the Guardians
14 . Spider-Man 2
15 . Horse Camp
16 . The Godfather
17 . World War Z
18 . Welcome to Mooseport
19 . Batman Begins
20 . Don Juan DeMarco
21 . Spaceballs
22 . On the Waterfront
23 . Batman
24 . Extreme Measures
25 . The Image Revolution
26 . Behind Enemy Lines
27 . Crimson Tide
28 . Nutty Professor II: The Klumps
29 . Hellboy II: The Golden Army
30 . Batman
